### ISSUE TITLE
link not shown in email settings

### ISSUE THREAD

**Issue by udarts** [WordImpress/woocommerce-preview-emails#1]
I have tried setting up the script for the preview emails, but nothing is shown.

I did everything described.

Do I miss anything?

Thanks

**Comment by fabianmarz** [comment]
Try it like this. Maybe your include path isn't correct.

``` php
$preview = __DIR__.'/woocommerce/emails/woo-preview-emails.php';
```

**Comment by udarts** [comment]
Thanks that worked.

**Comment by fabianmarz** [comment]
Are you able to close the issue?

**Comment by udarts** [comment]
done

**Comment by mathetos** [comment]
Glad you all got it sorted ;-)
