### ISSUE TITLE
working whit the woocommerce 2.6.3?

### ISSUE THREAD

**Issue by carmolim** [WordImpress/woocommerce-preview-emails#14]
Just tried to use with woocommerce 2.6.3 and didn't work :( any thoughts?

**Comment by g-anthony** [comment]
After the update did you re-copy the "emails" override folder to your theme?

**Comment by carmolim** [comment]
yep

**Comment by g-anthony** [comment]
What about the function reference, did you recheck that just in case?

**Comment by carmolim** [comment]
I tried again, and now is kind of working, when I enter in the woocommerce defaulf preview, the header and the footer aren't correct, and when I enter in the the preview emails, the footer and header are missing.

If I repace the footer and header from the woocommerce template, the default preview from woocommerce show the correct default template, in the other prevew everyting gets screwed up :(

**Comment by carmolim** [comment]
now I updated the header and footer parts from woocommerce and the header is showing correctly, but the content of the header, and the content from the order aren't :(

**Comment by mathetos** [comment]
Hey @carmolim Two things:

1) It sounds like you're missing STEP 2 from the Readme: https://github.com/WordImpress/woocommerce-preview-emails

2) I just did some major updates to get all the templates current with Woo version 2.6+ Update and go to "WooCommerce > Settings > Emails" and you'll see the new Preview email link section added there -- it's NOT the same link as the WooCommerce default preview link.

Thanks!
