### ISSUE TITLE
Show templates from plugins

### ISSUE THREAD

**Issue by renatonascalves** [WordImpress/woocommerce-preview-emails#16]
Templates added by plugins is not showing in the list because the plugin fetches only the core templates from WooCommerce.

Maybe that's the intention. Not sure!

**Comment by angieellis** [comment]
I have custom templates too. Mine are in the wp-content/themes/theme_name/woocommerce/emails directory. To include them, I added this code: 
`		
                $default_path = WC()->plugin_path() . '/templates/';
		$files   = scandir( $default_path . 'emails' );

		$custom_path = get_theme_file_path() . '/woocommerce/';
		$custom_files = scandir( $custom_path . 'emails' );

		$exclude = array(
			'.',
			'..',
			'email-header.php',
			'email-footer.php',
			'email-styles.php',
			'email-order-items.php',
			'email-addresses.php',
			'email-customer-details.php',
			'plain',
			'woo-preview-emails.php',
			'img'
		);

		$list = array_diff( array_merge( $files, $custom_files), $exclude);
		sort($list);
`
Just replace the $custom_path with the path to your plugin templates directory and add any files to exclude in the $exclude array.

**Comment by renatonascalves** [comment]
Thank you! I can do that, but non-devs can't. It was good if the project developer could add this.

**Comment by KoolPal** [comment]
> 
> 
> I have custom templates too. Mine are in the wp-content/themes/theme_name/woocommerce/emails directory. To include them, I added this code:
> `
> $default_path = WC()->plugin_path() . '/templates/';
> $files = scandir( $default_path . 'emails' );
> 
> ```
> 	$custom_path = get_theme_file_path() . '/woocommerce/';
> 	$custom_files = scandir( $custom_path . 'emails' );
> 
> 	$exclude = array(
> 		'.',
> 		'..',
> 		'email-header.php',
> 		'email-footer.php',
> 		'email-styles.php',
> 		'email-order-items.php',
> 		'email-addresses.php',
> 		'email-customer-details.php',
> 		'plain',
> 		'woo-preview-emails.php',
> 		'img'
> 	);
> 
> 	$list = array_diff( array_merge( $files, $custom_files), $exclude);
> 	sort($list);
> ```
> 
> `
> Just replace the $custom_path with the path to your plugin templates directory and add any files to exclude in the $exclude array.

Where did you add this code?

**Comment by damiencarbery** [comment]
> Where did you add this code?
Probably to functions.php of the theme (wp-content/themes/theme_name/functions.php) but I don't see how it is being used - I don't see what action or filter is calling @angieellis code
