### ISSUE TITLE
95% working but throwing errors

### ISSUE THREAD

**Issue by j-mccarthy** [WordImpress/woocommerce-preview-emails#6]
Hi, could be me but I'm receiving the following errors.

`Notice: Undefined index: order in /Users/G-Remble/Sites/chestnutsbnb.dev/wp-content/themes/chestnutsbnb/woocommerce/emails/woo-preview-emails.php on line 56`

`Notice: Undefined variable: email_heading in /Users/G-Remble/Sites/chestnutsbnb.dev/wp-content/themes/chestnutsbnb/woocommerce/emails/woo-preview-emails.php on line 58`

All files are in my child theme and to be clear are included in the functions.php file using get_stylesheet_directory();

I'm running WordPress 4.3.1 and Woocommerce 2.4.6. 

The link on the "Email Options" page is there and sends me to the correct page, and the preview page renders 95% but with errors which seem to preventing the content to load.

Does it seem like this is an error in implementation on my side? I apologise in advance if it is, I've not made many deep customisations to the theme yet so reporting here whilst I investigate the issue.

**Comment by j-mccarthy** [comment]
Sorry I forgot to mention I'm working locally with MAMP

**Comment by mathetos** [comment]
I need to do some basic updates to this for the latest versions of the WooCommerce email templates. I'll review and see if I can duplicate this issue. I did just implement this on a site the other day though and didn't encounter that. We'll see though, thanks for the heads up.

**Comment by j-mccarthy** [comment]
No problem. 

I have since tested on a fresh install using WordPress 4.3.1, Woocommerce 2.4.7 and the Woo Storefront theme 1.5.1 with a clean child theme with style.css with necessary comments and blank functions.php file apart from the get_stylesheet function.

I'm still getting the same errors.

**Comment by mathetos** [comment]
I've updated this library to support the latest WooCommerce 2.6+ Update and all should be fine. Thanks!
