### ISSUE TITLE
Call to undefined function wc_get_template()

### ISSUE THREAD

**Issue by azeemdwt** [WordImpress/woocommerce-preview-emails#8]
Hi, 

I am getting error 

"Call to undefined function wc_get_template() in [path to theme]/woocommerce/emails/email-header.php on line 32
"

System info

WC Version:                 2.0.13
WC Database Version:    2.0.13
WP Version:         WP 3.6
Web Server Info:    Apache/2.4.12 (Ubuntu)
PHP Version:            5.5.26
MySQL Version:  5.5.28-0ubuntu0.12.04.2-log

Please help in this regard.

**Comment by mathetos** [comment]
Yes, this needs to be updated to the latest template files of WooCommerce. I assume you're running WooCommerce 2.4+ 

Hoping to knock that out sometime next week. But you can also compare the current with the WooCommerce template and pull over the new parts. Between that, or waiting for me to update next week sometime, that's what I can do for now.

**Comment by azeemdwt** [comment]
Thanks for prompt response. I am using WooCommerce 2.0.13 version.

**Comment by mathetos** [comment]
I've updated this library to support the latest WooCommerce 2.6+ Update and all should be fine. Thanks!
