### ISSUE TITLE
customer details not showing

### ISSUE THREAD

**Issue by conflicker** [WordImpress/woocommerce-preview-emails#9]
I see that a global variable named $order was declared in woo-preview-emails and passed it when calling wc_get_template function. I'm just wondering why it's not showing in the preview.

**Comment by mathetos** [comment]
This code is now a few versions behind the current WooCommerce version. I plan to update it, but PR's are welcome

**Comment by mathetos** [comment]
I've updated this library to support the latest WooCommerce 2.6+ Update and all should be fine. Thanks!
